stages:
  data_ingestion:
    cmd: python src/mlProject/pipeline/stage_01_data_ingestion.py
    deps: 
      - src/mlProject/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/olist_customers_dataset.csv
  
  data_preprocessing:
    cmd: python src/mlProject/pipeline/stage_02_data_preprocessing.py
    deps:
      - src/mlProject/pipeline/stage_02_data_preprocessing.py
      - config/config.yaml
      - params.yaml
    params:
      - features_to_drop  
      - categorical_features  
    outs:
      - artifacts/data_preprocessing/preprocessed_data.csv
  
  data_transformation:
    cmd: python src/mlProject/pipeline/stage_03_data_transformation.py
    deps:
      - src/mlProject/pipeline/stage_03_data_transformation.py
      - config/config.yaml
    outs:
      - artifacts/data_transformation/train.csv
      - artifacts/data_transformation/test.csv

  model_trainer:
    cmd: python src/mlProject/pipeline/stage_04_model_training.py
    deps:
      - src/mlProject/pipeline/stage_04_model_training.py
      - config/config.yaml
      - params.yaml  
    params:
      - XGBRegressor
      - TARGET_COLUMN  
    outs:
      - artifacts/model_trainer/model.joblib
    
  model_evaluation:
    cmd: python src/mlProject/pipeline/stage_05_model_evaluation.py
    deps:
      - src/mlProject/pipeline/stage_05_model_evaluation.py
      - config/config.yaml
      - artifacts/model_trainer/model.joblib  
    outs:
      - artifacts/model_evaluation/metrics.json  
  
metrics:
  - artifacts/model_evaluation/metrics.json
    