XGBRegressor:
  objective: 'reg:squarederror'
  n_estimators: 100
  learning_rate: 0.1
  max_depth: 5
  min_child_weight: 1
  subsample: 0.8
  colsample_bytree: 0.8
  reg_lambda: 1

features_to_drop : [
    'order_purchase_timestamp','order_approved_at','order_delivered_carrier_date','order_delivered_customer_date','order_estimated_delivery_date',
    'customer_zip_code_prefix','shipping_limit_date','product_weight_g','product_length_cm','product_height_cm','product_width_cm',
    'order_id', 'customer_id', 'payment_sequential','customer_unique_id', 'order_item_id', 'product_id',
    'seller_id','review_comment_message'
  ]

categorical_features : [
    'order_status',
    'product_category_name',
    'product_category_name_english',
    'customer_city',
    'customer_state',
    'payment_type'
  ]

TARGET_COLUMN:
  name: review_score