artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/bot69dude/image_segment/raw/main/olist_customers_dataset.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_preprocessing:
  root_dir: artifacts/data_preprocessing
  data_dir: artifacts/data_ingestion/olist_customers_dataset.csv


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_preprocessing/preprocessed_data.csv


model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib
